Update for byte swapping function rename in Xorg 1.20
Fixes compiler warnings:

vloaduc.c: In function ‘verite_load_ucfile’:
vloaduc.c:35:17: warning: implicit declaration of function ‘lswaps’; did you mean ‘swaps’? [-Wimplicit-function-declaration]
   35 | #define SW16(x) lswaps(x)
      |                 ^~~~~~
vloaduc.c:103:6: note: in expansion of macro ‘SW16’
  103 |   sz=SW16(ehdr.e_phentsize);
      |      ^~~~
vloaduc.c:34:17: warning: implicit declaration of function ‘lswapl’; did you mean ‘swapl’? [-Wimplicit-function-declaration]
   34 | #define SW32(x) lswapl(x)
      |                 ^~~~~~
vloaduc.c:113:42: note: in expansion of macro ‘SW32’
  113 |         if (seek_and_read_hdr(fd, pphdr, SW32(ehdr.e_phoff), sz, num)) {
      |                                          ^~~~

Signed-off-by: Alan Coopersmith <alan.coopersmith@oracle.com>